'''
File: tree_visualization.py
The purpose of this file is to visualize primitive trees generated by the genetic algorithm.
it takes as an argument a primitive tree generated by gp.genFull() pr gp.genHalfAndHald() and saved to a variable

eg:
expr = gp.genFull(primitive_set, min_=3, max_=8)
tree = gp.PrimitiveTree(expr)
'''
from genetic_programming.primitives import primitive_set
from deap import gp
import matplotlib.pyplot as plt
import networkx as nx
import pygraphviz as pgv

def visualize_tree(tree):

    nodes, edges, labels = gp.graph(tree)
    g = pgv.AGraph()
    for node in nodes:
        g.add_node(node, label=labels[node])

    g.add_edges_from(edges)
    g.layout(prog="dot")
    g.draw('results/tree_visualizations/tree_visualization.png')